### ISSUE TITLE
[Idea] Use Favicon for All Your Demos

### ISSUE THREAD

**Issue by kookma** [EvidentlyCube/TW5-TiddlerCompletion#1]
I would recommend to use favicon for all your demos.

TW now supports both icon, svg, png, ... as favicon!

An image with correct size saved as $:/favicon.ico acts as the webpage favicon!

Thank you for all your great plugins :-)

**Comment by EvidentlyCube** [comment]
It was one of those "I am too lazy to do it" things but now that I am called out I guess it's too late to hide behind laziness :).

I've added a favicon to the [Showcase repo](https://github.com/EvidentlyCube/TW5-PluginShowcase), thanks for the suggestion!
