### ISSUE TITLE
[Idea] Use Caption Field for Registered Triggers Tiddlers

### ISSUE THREAD

**Issue by kookma** [EvidentlyCube/TW5-TiddlerCompletion#2]
While the Auto Complete works great, the below suggestion may enhance the setting page. Right now the `Registered Triggers` is shown as below:

![img_114_msedge](https://user-images.githubusercontent.com/830394/205087827-cc266552-e4e3-4eaf-b629-9e83d8a6b5c7.png)

In `$:/plugins/EvidentlyCube/AutoComplete/Settings`, you may change the `Registered Triggers` as belows! Note to the cascade $view. The caption will be shown by default, if missing, the tiddler title is used. Also note to `sortan[title]` in the $list filter.

```
<ul>
	<$list filter="[all[shadows+tiddlers]tag[$:/tags/EC/AutoComplete/Trigger]!is[draft]sortan[title]]">
		<li><$link to=<<currentTiddler>>>
		<$view field=caption>
		  <$view field=title/>
		</$view>
		</$link> (Trigger <code>{{!!trigger}}</code>)
		</li>
	</$list>
	<li><$button actions=<<action-new-trigger>>>Create a new trigger</$button></li>
</ul>
```

**Comment by EvidentlyCube** [comment]
Thanks, I've added this in 1.0.13 which never got released because I was already working on 1.0.14 which is out now :).
