### ISSUE TITLE
[Idea] Lets Scroll in Entries on Auto Complete Window

### ISSUE THREAD

**Issue by kookma** [EvidentlyCube/TW5-TiddlerCompletion#3]
Sometime users have forgotten the key to find the correct entry, for example you want to insert a wikitext link, Auto Complete shows 8 first entries or whatever number you set in Auto Complete settings!

A rough suggestion is: One can click on the `...` at the bottom of opened windows and Auto Complete shows more items, or turn on vertical scrollbar and lets user scroll among entries.

--_Ignore if this makes UI noisy or distracting..._

**Comment by EvidentlyCube** [comment]
I've added something like this in 1.0.14 which is now released - no decent way to use mouse to scroll the completion window at the moment, but keyboard allows scrolling. Thanks for the suggestion!
