### ISSUE TITLE
[Question] Compressing with Uglify and Some Warning

### ISSUE THREAD

**Issue by kookma** [EvidentlyCube/TW5-TiddlerCompletion#4]
I use uglify to compress customized edition of TW and it is very effective and makes size reduction in order of 30 to 50% (4.3MB -> 2.7MB,...)

When I compress a TW with Auo Complete installed, I get few warnings:

----
Failed to compress [$:/plugins/EvidentlyCube/AutoComplete/completion-api.js](https://github.com/EvidentlyCube/TW5-AutoComplete/issues/new#%24%3A%2Fplugins%2FEvidentlyCube%2FAutoComplete%2Fcompletion-api.js)

message: Unexpected token: punc «:», expected: punc «;»
line: 93
col: 24
pos: 2500

---
Failed to compress [$:/plugins/EvidentlyCube/AutoComplete/integration-core.js](https://github.com/EvidentlyCube/TW5-AutoComplete/issues/new#%24%3A%2Fplugins%2FEvidentlyCube%2FAutoComplete%2Fintegration-core.js)

message: Unexpected token: name «of», expected: punc «;»
line: 209
col: 19
pos: 7352

---
Failed to compress [$:/plugins/EvidentlyCube/AutoComplete/textarea-caret-position.js](https://github.com/EvidentlyCube/TW5-AutoComplete/issues/new#%24%3A%2Fplugins%2FEvidentlyCube%2FAutoComplete%2Ftextarea-caret-position.js)

message: Unexpected token: name «of», expected: punc «;»
line: 88
col: 17
pos: 2489

You can ignore these as Uglify compresses the TW and the output is a working wiki!
I am not familiar with JS edition, but seems these are something related to JS.

**Comment by EvidentlyCube** [comment]
The first one is most likely an actual mistake in the JS.
The other two seems to be newer JS features that the uglifier you use just not recognizing - I am using [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) there.

**Comment by kookma** [comment]
Thank you for clarification!

**Comment by EvidentlyCube** [comment]
I am reopening since the first one is an actual mistake **I made** in the JS (I ate the **I made** part in my last comment), something I need to at least look into :).

**Comment by EvidentlyCube** [comment]
Okay, checked it properly and I think the first fail is caused by using backticks for template strings. Which means it's all good,
